### ISSUE TITLE
Code convention for simple scripts in browserify

### ISSUE THREAD

**Issue by bartaz** [canonical-ols/style-guides#2]
The aim to browserify all the scripts leads to the question how we 'migrate' simple scripts into CommonJS modules supported by browserify.

We want to keep the simplicity while keeping new modules testable.

Possible options we discussed are as follows:

1) Export constructor directly
----------------------------------------

In module code:

```js
var MyModule = function(){};
module.exports = MyModule;
```

In template:
```html
<script scr="mymodule.js"></script>
<script>
    var MyModule = require('mymodule');
    new MyModule();
</script>
```

#### Pros:
* almost self documenting (you don't need to know module API, just require it and instantiate directly)

#### Cons:
 * same as `new (require('mymodule'))()` just in 2 lines for better readability

2) Export a named constructor
-------------------------------------------

In module code:

```js
var MyModule = function(){};
module.exports.MyModule = MyModule;
```

In template:
```html
<script scr="mymodule.js"></script>
<script>
    new (require('mymodule').MyModule)();
</script>
```

#### Pros:
* seems to be a common convention in node.js modules

#### Cons:
 * almose as bad as one-liner as `new (require('mymodule'))()`

3) Export an instance
------------------------------

In module code:

```js
var MyModule = function(){};
module.exports = new MyModule();
```

In template:
```html
<script scr="mymodule.js"></script>
<script>
    require('mymodule');
</script>
```

#### Pros:
* self documenting, just a simple require
* no 'boilerplate' code of creating a variable and instance

#### Cons:
* require caches modules, so each require will return same instance of a module that may lead to unexpected behaviour and problems with testing

4) Export a factory method (with a name convention)
-----------------------------------------------------------------------

```js
var MyModule = function(){};
module.exports.create = function() {
    return new MyModule();
};
```

In template:
```html
<script scr="mymodule.js"></script>
<script>
    require('mymodule').create();
</script>
```

#### Pros:
* almost self documenting (you just need to know the convention to use `create` as a factory method name
* no 'boilerplate' code of creating a variable and instance

#### Cons:
* require caches modules, so each require will return same instance of a module that may lead to unexpected behaviour and problems with testing

Autorun browserify bundle
----------------------------------------

Additional issue with all examples above is that they need additional `<script>` to require/instantiate a module. This can be avoided by moving the code that runs the module into browserified bundle itself.

So a main script in the bundle will still be our module (using any convention we want):

```js
var MyModule = function(){};
module.exports.create = function() {
    return new MyModule();
};
```

In entry.js of a bundle:
```js
require('./mymodule').create();
```

In template:
```html
<script scr="mymodule.js"></script>
```

#### Pros: 
* no need for additional require script in HTML

#### Cons:
* even simple script becomes 2-file bundle

**Comment by earnubs** [comment]
In the 'cons' section of Autorun browserify bundle, do we need 2 bundles? Can't we create one bundle, but from 2 files, with the main script being loaded as:

`require('./mymodule').create();`

I guess the issue then is testability?

This is what I was thinking about, along similar lines:

```js

function MyModule() {};

module.exports = function(flag, config) {
  if (flag) {
    // return a constructor only, for testing
    return MyModule;
  } else {
    // by default instantiate and run, so no script block required in the template
    return new MyModule(config);
  }
}
```

**Comment by bartaz** [comment]
@earnubs I meant that simple script will became a one bundle of 2 files. Made it more clear and fixed the require to `require('./mymodule')` as you suggested.

About the testability - I don't know how our current test setup is - if tests can have access to the 'inside' of the bundle (do `require(./mymodule)` instead of `require('./entry')`) than it shouldn't be an issue.

**Comment by earnubs** [comment]
I found this argument persuasive:
https://codinginthetrenches.com/2015/10/03/nodejs-modules-should-export-object-constructors/

**Comment by earnubs** [comment]
... but exporting constructors, while simple, also leaves a lot of unnecessary furniture lying around in templates; it would be possible with the browserify option to have only a script loaded and no <script> block to instantiate in template, with no pollution of global scope, no chance of human error in instantiation
