### ISSUE TITLE
What to do with legacy code?

### ISSUE THREAD

**Issue by earnubs** [canonical-ols/style-guides#3]
When we come across older bits of code, should we conform to the style in context or
refactor to our new style? I think the latter is probably adding an overhead we generally don't want, except in special circumstances like YUI which as a dependency is something we want rid of (it adds time to bootstrapping, etc).

**Comment by bartaz** [comment]
Yes, if we want to focus on getting things done it would be best to avoid unnecessary refactoring.
But it would probably be the best to leave it for case to case judgement. If it's just a small one-file script it may be a good opportunity to update it when working on it. If it's a bigger module it would be best to avoid unnecessary work and possible bugs.

So I would agree that: new stuff should conform to the style guides and when working on older stuff just keep it as it is (unless the effort put into refactoring is not affecting the task being done).
